version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: betting-platform-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - betting-platform-network

  redis:
    image: redis:7-alpine
    container_name: betting-platform-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - betting-platform-network

networks:
  betting-platform-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
